/* Generated by AN DISI Unibo */ 
package it.unibo.ctxrobotcleaner
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "130.136.113.133", this, "sonarqak.pl", "sysRules.pl", "ctxrobotcleaner"
	)
	//JAN Facade
	//JAN24 Display
}

