/* Generated by AN DISI Unibo */ 
package it.unibo.ffdcircuit

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Ffdcircuit ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="handleset1",cond=whenDispatch("set1"))
					transition(edgeName="t019",targetState="handlereset1",cond=whenDispatch("reset1"))
					transition(edgeName="t020",targetState="handleset0",cond=whenDispatch("set0"))
					transition(edgeName="t021",targetState="handlereset0",cond=whenDispatch("reset0"))
				}	 
				state("handleset1") { //this:State
					action { //it:State
						CommUtils.outgreen("set S=1")
						forward("oni2", "oni2(1)" ,"norset" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="handleset1",cond=whenDispatch("set1"))
					transition(edgeName="t023",targetState="handlereset1",cond=whenDispatch("reset1"))
					transition(edgeName="t024",targetState="handleset0",cond=whenDispatch("set0"))
					transition(edgeName="t025",targetState="handlereset0",cond=whenDispatch("reset0"))
				}	 
				state("handlereset1") { //this:State
					action { //it:State
						CommUtils.outgreen("set R=1")
						forward("oni1", "oni1(1)" ,"norreset" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t026",targetState="handleset1",cond=whenDispatch("set1"))
					transition(edgeName="t027",targetState="handlereset1",cond=whenDispatch("reset1"))
					transition(edgeName="t028",targetState="handleset0",cond=whenDispatch("set0"))
					transition(edgeName="t029",targetState="handlereset0",cond=whenDispatch("reset0"))
				}	 
				state("handleset0") { //this:State
					action { //it:State
						CommUtils.outgreen("set S=0")
						forward("offi2", "offi2(1)" ,"norset" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t030",targetState="handleset1",cond=whenDispatch("set1"))
					transition(edgeName="t031",targetState="handlereset1",cond=whenDispatch("reset1"))
					transition(edgeName="t032",targetState="handleset0",cond=whenDispatch("set0"))
					transition(edgeName="t033",targetState="handlereset0",cond=whenDispatch("reset0"))
				}	 
				state("handlereset0") { //this:State
					action { //it:State
						CommUtils.outgreen("set R=0")
						forward("offi1", "offi1(1)" ,"norreset" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t034",targetState="handleset1",cond=whenDispatch("set1"))
					transition(edgeName="t035",targetState="handlereset1",cond=whenDispatch("reset1"))
					transition(edgeName="t036",targetState="handleset0",cond=whenDispatch("set0"))
					transition(edgeName="t037",targetState="handlereset0",cond=whenDispatch("reset0"))
				}	 
			}
		}
} 
